#!/bin/env sh

# Setup my dotfiles for a fresh Xubuntu installation.
# NOTE: This scripts assumes the dotfiles folder is at path ~/dotfiles

# Makes backup of current dotfiles
echo 'Making backup of current dotfiles...'
mkdir ~/dotfilesbak

if [ -f ~/.config/user-dirs.dirs ]; then mv ~/.config/user-dirs.dirs ~/dotfilesbak; fi
if [ -d ~/.config/i3 ]; then mv ~/.config/i3 ~/dotfilesbak; fi
if [ -d ~/.config/i3status ]; then mv ~/.config/i3status ~/dotfilesbak; fi
if [ -f ~/.gitconfig ]; then mv ~/.gitconfig ~/dotfilesbak; fi
if [ -f ~/.bashrc ]; then mv ~/.bashrc ~/dotfilesbak; fi
if [ -f ~/.aliases ]; then mv ~/.aliases ~/dotfilesbak; fi
if [ -d ~/.vim ]; then mv ~/.vim ~/dotfilesbak; fi
if [ -f ~/.vimrc ]; then mv ~/.vimrc ~/dotfilesbak; fi

echo 'Backup saved at ~/dotfilesbak path'

# Install git and download dotfiles from remote repository
# NOTE: ssh must be already configured for GitHub
echo 'Setting up git...'
sudo apt install -y git

echo 'Downloading dotfiles...'
git clone git@github.com:luanrvmood/dotfiles.git
ln -s ~/dotfiles/gitconfig ~/.gitconfig

# Update system default folders (Downloads, Music, Pictures, etc)
echo 'Setting up system folders...'
ln -s ~/dotfiles/dotconfig/user-dirs.dirs ~/.config/user-dirs.dirs
rm -r Desktop Downloads Music Pictures Public Videos Documents Templates
mkdir downloads tracks pics videos docs projects

# Install i3 and i3status
echo 'Setting up i3wm...'
sudo apt install -y i3
echo 'exec i3' > ~/.xinitrc
mkdir ~/.config/i3
mkdir ~/.config/i3status
ln -s ~/dotfiles/dotconfig/i3/config ~/.config/i3/config
ln -s ~/dotfiles/dotconfig/i3status/config ~/.config/i3status/config

# Uninstall xfce4 desktop stuffs and enable i3wm
echo 'Uninstalling xfce4 desktop environment...'
sudo apt remove --purge xfdestkop4 xfdestkop4-data
xfconf-query -c xfce4-session -p /sessions/Failsafe/Client0_Command -t string -sa i3

echo 'Installing feh for wallpaper settings...'
sudo apt install -y feh

i3-msg reload

# Setup bash and aliases
echo 'Setting up the shell (bash)...'
ln -s ~/dotfiles/shell/aliases ~/.aliases
ln -s ~/dotfiles/shell/bashrc ~/.bashrc
ln -s ~/dotfiles/shell/inputrc ~/.inputrc

echo 'Setting up JetBrains Mono font...'
curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh | bash -

echo 'Basic system configured! Installing tools...'

# Install Vim from source (with OS clipboard support) and setup
# Dracula colorscheme (https://github.com/dracula/vim)
#
# NOTE: Need to update /etc/apt/sources.list with additional deb-src URIS to
# install Vim dependencies
echo 'Setting up Vim...'
sudo apt build-dep -y vim
git clone git@github.com:vim/vim.git
cd vim
./configure --with-x
make
sudo make install
cd
rm -rf vim
ln -s ~/dotfiles/editor/vimrc ~/.vimrc

mkdir -p ~/.vim/pack/themes/start
cd ~/.vim/pack/themes/start
git clone https://github.com/dracula/vim.git dracula
cd

echo 'Setting up JavaScript syntax...'
mkdir -p ~/.vim/syntax/start/
cd ~/.vim/syntax/start/
git clone git@github.com:pangloss/vim-javascript.git
cd

echo 'Setting up TypeScript syntax...'
mkdir -p ~/.vim/syntax/start/
cd ~/.vim/syntax/start/
git clone git@github.com:leafgarland/typescript-vim.git
cd

echo 'Setting up React/JSX syntax...'
mkdir -p ~/.vim/syntax/start
cd ~/.vim/syntax/start
git clone git@github.com:MaxMEllon/vim-jsx-pretty.git
cd

echo 'Setting up Python syntax...'
mkdir -p ~/.vim/after/syntax/
ln -s ~/dotfiles/dotvim/after/syntax/python.vim ~/.vim/after/syntax/python.vim

echo 'Vim is ready to use!'

echo 'Installing asdf for manage languages installations...'
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
cd ~/.asdf
git checkout "$(git describe --abbrev=0 --tags)"

echo 'Setting up Python environment...'
asdf plugin add python
asdf install python latest

echo 'Setting up Ruby environment...'
asdf plugin add ruby
asdf install ruby latest

echo 'DONE!'
