#!/bin/env sh

# Setup my dotfiles for a fresh Xubuntu installation.
# Important: this script requires to have ssh configured for GitHub.

# Few steps that need to be run manually:
# update /etc/apt/sources.list with additional deb-src URIS
# run wget https://raw.githubusercontent.com/luanrvmood/dotfiles/main/setup -O setup
# run chmod +x setup
# run ./setup

echo 'Installing Git...'
sudo apt update
sudo apt install -y git

echo 'Downloading dotfiles...'
git clone git@github.com:luanrvmood/dotfiles.git ~/.dotfiles
ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig

echo 'Setting up JetBrains Mono font...'
sudo apt install -y curl
curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh | bash -

echo 'Setting up the shell...'
if [ -f ~/.aliases ]; then
  rm ~/.aliases
fi

if [ -f ~/.bashrc ]; then
  rm ~/.bashrc
fi

if [ -f ~/.config/xfce4/terminal/terminalrc ]; then
  rm ~/.config/xfce4/terminal/terminalrc
fi

ln -s ~/.dotfiles/shell/aliases ~/.aliases
ln -s ~/.dotfiles/shell/bashrc ~/.bashrc
ls -s ~/.dotfiles/shell/terminalrc ~/.config/xfce4/terminal/terminalrc
# ln -s ~/.dotfiles/shell/inputrc ~/.inputrc

echo 'Setting up Vim...'
sudo apt build-dep -y vim
git clone git@github.com:vim/vim.git ~/vim
cd ~/vim
./configure --with-x
make
sudo make install
cd
rm -rf vim
ln -s ~/.dotfiles/editor/vimrc ~/.vimrc

echo 'Setting up Dracula for Vim...'
mkdir -p ~/.vim/pack/themes/start
cd ~/.vim/pack/themes/start
git clone https://github.com/dracula/vim.git dracula
cd

echo 'Setting up NERDTRee for Vim...'
mkdir -p ~/.vim/plugins/start/
cd ~/.vim/plugins/start/
git clone git@github.com:preservim/nerdtree.git
cd

echo 'Setting up JavaScript syntax for Vim...'
mkdir -p ~/.vim/syntax/start/
cd ~/.vim/syntax/start/
git clone git@github.com:pangloss/vim-javascript.git
cd

echo 'Setting up TypeScript syntax for Vim...'
mkdir -p ~/.vim/syntax/start/
cd ~/.vim/syntax/start/
git clone git@github.com:leafgarland/typescript-vim.git
cd

echo 'Setting up React/JSX syntax for Vim...'
mkdir -p ~/.vim/syntax/start
cd ~/.vim/syntax/start
git clone git@github.com:MaxMEllon/vim-jsx-pretty.git
cd

# TODO: fetch Python syntax file from remote
# echo 'Setting up Python syntax for Vim...'
# mkdir -p ~/.vim/after/syntax/
# ln -s ~/dotfiles/dotvim/after/syntax/python.vim ~/.vim/after/syntax/python.vim

echo 'Installing asdf for managing development environments...'
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
cd ~/.asdf
git checkout "$(git describe --abbrev=0 --tags)"

# NOTE: need to set installed version globally:
# asdf global nodejs <VERSION> or asdf global yarn <VERSION>
echo 'Setting up Node environment...'
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdf plugin add nodejs
asdf install nodejs latest
asdf plugin add yarn
asdf install yarn latest

echo 'Setting up system folders...'
cd

if [ -f ~/.config/user-dirs.dirs ]; then
  rm ~/.config/user-dirs.dirs
fi

ln -s ~/.dotfiles/config/user-dirs.dirs ~/.config/user-dirs.dirs
rm -rf Desktop Downloads Music Pictures Public Videos Documents Templates
mkdir downloads docs repos

echo 'Setting up i3wm...'
sudo apt install -y i3
echo 'exec i3' > ~/.xinitrc
mkdir ~/.config/i3
mkdir ~/.config/i3status
ln -s ~/.dotfiles/config/i3/config ~/.config/i3/config
ln -s ~/.dotfiles/config/i3status/config ~/.config/i3status/config

echo 'Uninstalling xfce4 desktop environment...'
sudo apt remove --purge -y xfdesktop4 xfdesktop4-data
xfconf-query -c xfce4-session -p /sessions/Failsafe/Client0_Command -t string -sa i3

# echo 'Installing feh for wallpaper settings...'
# sudo apt install -y feh
#
# echo 'Setting up Python environment...'
# sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
# asdf plugin add python
# asdf install python latest
#
# echo 'Setting up Ruby environment...'
# asdf plugin add ruby
# asdf install ruby latest
#
# echo 'Installing Typora...'
# wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
# sudo add-apt-repository 'deb https://typora.io/linux ./'
# sudo apt update
# sudo apt install -y typora

echo 'Installing Google Chrome...'
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O ~/downloads/google-chrome.deb
sudo apt install ~/downloads/google-chrome
rm ~/downloads/google-chrome

echo 'DONE!'
echo 'Restarting...'
sudo reboot
