#!/bin/env sh

# Setup my dotfiles for a fresh Xubuntu installation.
# Important: this script requires to have ssh configured for GitHub.

# Few steps that need to be run manually:
# update /etc/apt/sources.list with additional deb-src URIS
# run wget https://raw.githubusercontent.com/luanrvmood/dotfiles/main/setup -O setup
# run chmod +x setup
# run ./setup

# TODO: CHECK IF 2 STEPS BELOW STILL NECCESSARY
echo 'Setting up Node environment...'
sudo apt install -y dirmngr gpg gawk
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest
asdf plugin add yarn
asdf install yarn latest
asdf global yarn latest

echo 'Installing Docker...'
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io

echo 'Installling docker-compose...'
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o ~/.local/bin/docker-compose
sudo chmod +x ~/.local/bin/docker-compose

echo 'Installing Typora...'
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt update
sudo apt install -y typora

echo 'Installing Google Chrome...'
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O ~/downloads/google-chrome.deb
sudo apt install ./downloads/google-chrome.deb
rm ~/downloads/google-chrome.deb

echo 'Installing youtube-dl...'
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ~/.local/bin/youtube-dl
chmod +x ~/.local/bin/youtube-dl

echo 'Setting up screenshot utilities...'
sudo apt install -y maim xclip

echo 'Setting up system folders...'
cd
ln -sf ~/.dotfiles/config/user-dirs.dirs ~/.config/user-dirs.dirs
rm -rf Desktop Downloads Music Pictures Public Videos Documents Templates
mkdir downloads docs pics codes tracks tv

echo 'Setting up i3wm...'
sudo apt install -y i3
echo 'exec i3' > ~/.xinitrc
mkdir ~/.config/i3
mkdir ~/.config/i3status
ln -s ~/.dotfiles/config/i3/config ~/.config/i3/config
ln -s ~/.dotfiles/config/i3status/config ~/.config/i3status/config

echo 'Uninstalling xfce4 desktop environment...'
sudo apt remove --purge -y xfdesktop4 xfdesktop4-data
xfconf-query -c xfce4-session -p /sessions/Failsafe/Client0_Command -t string -sa i3
